import React from 'react';
import { Copy, Share2, RefreshCw } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface PoemDisplayProps {
  poem: string | null;
  isLoading: boolean;
  onReset: () => void;
}

export const PoemDisplay: React.FC<PoemDisplayProps> = ({ poem, isLoading, onReset }) => {
  const handleCopy = () => {
    if (poem) {
      navigator.clipboard.writeText(poem);
    }
  };

  if (isLoading) {
    return (
      <div className="h-full min-h-[400px] flex flex-col items-center justify-center p-8 bg-white rounded-xl shadow-sm border border-gray-100">
        <div className="relative w-16 h-16 mb-6">
          <div className="absolute top-0 left-0 w-full h-full border-4 border-gray-200 rounded-full"></div>
          <div className="absolute top-0 left-0 w-full h-full border-4 border-accent rounded-full border-t-transparent animate-spin"></div>
        </div>
        <h3 className="text-xl font-serif text-gray-800 mb-2">Consulting the Muse</h3>
        <p className="text-gray-500 text-center max-w-sm animate-pulse">
          Analyzing imagery, weaving metaphors, and crafting your verses...
        </p>
      </div>
    );
  }

  if (!poem) {
    return (
      <div className="h-full min-h-[400px] flex flex-col items-center justify-center p-8 bg-gray-50 rounded-xl border border-dashed border-gray-300 text-gray-400">
        <span className="italic font-serif text-lg">Your poem will appear here...</span>
      </div>
    );
  }

  return (
    <div className="relative h-full bg-white p-8 md:p-12 rounded-xl shadow-lg border border-gray-100 flex flex-col">
      <div className="absolute top-4 right-4 flex gap-2">
        <button 
          onClick={handleCopy}
          className="p-2 text-gray-400 hover:text-accent hover:bg-gray-50 rounded-full transition-colors"
          title="Copy to clipboard"
        >
          <Copy size={18} />
        </button>
        <button 
            onClick={onReset}
            className="p-2 text-gray-400 hover:text-accent hover:bg-gray-50 rounded-full transition-colors"
            title="Generate New"
        >
            <RefreshCw size={18} />
        </button>
      </div>

      <div className="prose prose-stone prose-lg max-w-none font-serif text-ink leading-relaxed flex-grow overflow-y-auto pr-2 custom-scrollbar">
        <ReactMarkdown
            components={{
                h1: ({node, ...props}) => <h1 className="text-2xl md:text-3xl font-bold text-center text-accent mb-8" {...props} />,
                h2: ({node, ...props}) => <h2 className="text-xl font-semibold text-center mb-6" {...props} />,
                p: ({node, ...props}) => <p className="mb-4 whitespace-pre-wrap" {...props} />,
            }}
        >
            {poem}
        </ReactMarkdown>
      </div>

      <div className="mt-8 pt-6 border-t border-gray-100 flex justify-center">
        <div className="flex items-center gap-2 text-sm text-gray-400 italic">
          <span>Generated by Gemini</span>
        </div>
      </div>
    </div>
  );
};
